sudo: required
language: c
services:
- docker
before_install:
- docker pull tg9541/docker-sdcc:V3.8.4
install:
- docker run -v `pwd`:/home tg9541/docker-sdcc:3.8.4 /bin/sh -c "sdcc --version ;
  sstm8 -version"
script: docker run -v `pwd`:/home tg9541/docker-sdcc:V3.8.4 /bin/sh -c "cd /home &&
  make simload && make zip && cat SWIMCOM-forth.ihx"
deploy:
  provider: releases
  api_key:
    secure: zAu5q6+9+zdC8weWy/xNQtuJb3TYQ9bMdiJuW80WcW2e/5xPsY9BM4rpz5r4XeFP/9IsdZhn3ZpTH1+KTZljpQwa+W1UI/OMgGMh4LzMpWawGQn8IZni3da57VTsA+EScMxVXRoRel3AfgANMKDFIhWvmj6klbj1Uw1t6fD69iw1I6sU4fKXvN3DpsPJmx4LtExHPonmZ1ikB08bDkMryo/GxWfTYlscL1CAD4Ea3O+fcWsV2X5Vne89KsL50UgheegvggbnJifXs/Lj6gBaNHIyO0peoIrxgKaTNb344yfHtEwS7JutfD5GLft7fte13doLOsrPjDDNjC0q7hDN8lCk3Aa+vgbQhudmYxW8bzTqY2vpitIoU5XTpmOsC1VFs6c7N2t3v/+uDNXZJoXWL1Nh9WnsL3j7SoBpPmPFzZ8k2Fly5WiSFI07dR2XzlXzlPBvp1ae6Rc71XH+FuPSvHQnfI99PnkozIIXZnN6lcrbN9v4oSzZ8b77l2LEH4gJDtC+gdAvXHOyD+X1JoGdxYDqZGGXOT+ecwge3gDmdzy+34n4q9qj5mqtZALrqOJMl+8z21LZ/B4nUzM1L5lclfwcO5PiMAv3LSQ7wDzFNrygpnCQi71cwn5CPs/78+xgHvnPFOeZMr/FOZL5dv/zylubIOBW1WWSX9fGB8Yt3X4=
  file: SWIMCOM-forth.zip
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: TG9541/stm8ef-modbus
